Repository open-telemetry/opentelemetry.io, pull requests merged in 2022-11, with the labels that each got.

#1877 Frontend Overhaul blog post
  content/en/blog/2022/frontend-overhaul/collector-cors-config.png
  content/en/blog/2022/frontend-overhaul/data-flow.png
  content/en/blog/2022/frontend-overhaul/diagram.png
  content/en/blog/2022/frontend-overhaul/index.md
  content/en/blog/2022/frontend-overhaul/jaeger.png
  content/en/blog/2022/frontend-overhaul/new-design.png
  content/en/blog/2022/frontend-overhaul/old-design.png
  content/en/blog/2022/frontend-overhaul/technologies.png
Labels: blog

#1969 Fix some typos and grammar in /exporters.md
  content/en/docs/instrumentation/js/exporters.md
Labels: sig:javascript

#1978 Specification: handle spec-local paths into experimental directory
  scripts/adjust-spec-pages.pl
Labels: infrastructure

#1979 Update monthly End User Discussion Group meetings copy and add dates
  content/en/community/end-user/discussion-group.md
Labels: end-user space

#1981 Drop temporary spec redirect rule
  layouts/index.redirects
Labels: cleanup/refactoring

#1891 Adding TypeScript to "Getting Started"
  content/en/docs/instrumentation/js/getting-started/browser.md
  content/en/docs/instrumentation/js/getting-started/nodejs.md
Labels: sig:javascript

#1974 Add Serverless section with AWS Lambda docs
  content/en/docs/instrumentation/js/serverless.md
Labels: sig:javascript

#1994 Bring ruby manual instrumentation docs up to par with rest of languages
  content/en/docs/instrumentation/ruby/getting-started.md
  content/en/docs/instrumentation/ruby/manual.md
Labels: sig:ruby

#2037 JS Metrics - simple docs
  content/en/docs/instrumentation/js/instrumentation.md
Labels: sig:javascript

#2053 Add apiclarity exporter & tortoiseORM instrumentation to registry
  content/en/registry/collector-exporter-apiclarity.md
  content/en/registry/instrumentation-python-tortoiseorm.md
Labels: registry
