Repository open-telemetry/opentelemetry.io, pull requests merged in 2022-03, with the labels that each got.

#1182 Normalize line lengths in python docs
  content/en/docs/instrumentation/python/_index.md
  content/en/docs/instrumentation/python/automatic.md
  content/en/docs/instrumentation/python/distro.md
  content/en/docs/instrumentation/python/getting-started.md
Labels: cleanup/refactoring

#1186 Update Hugo to 0.93.2, and other modules
  package.json
Labels: infrastructure

#1190 Registry form: use simple labels rather than i18n keys
  i18n/en.toml
  layouts/registry/list.html
Labels: cleanup/refactoring

#1191 Remove workaround from baseof.html
  layouts/_default/baseof.html
Labels: infrastructure, cleanup/refactoring

#1197 Copyedits for TroublesShooting Node.JS blog entry
  content/en/blog/2022/troubleshooting-nodejs.md
Labels: copyedit

#1208 Concepts > Instr libs: copyedits
  content/en/docs/concepts/instrumenting-library.md
Labels: copyedit

#1220 Settle on Node.js name, and use it consistently
  content/en/blog/2022/troubleshooting-nodejs.md
  content/en/docs/instrumentation/_index.md
  content/en/docs/instrumentation/js/_index.md
  content/en/docs/instrumentation/js/getting-started/_index.md
  content/en/docs/instrumentation/js/getting-started/nodejs.md
  content/en/docs/instrumentation/js/instrumentation.md
  content/en/docs/migration/opentracing.md
Labels: copyedit, cleanup/refactoring

#1223 Refine make-public script
  Makefile
  package.json
Labels: infrastructure

#1213 updated build command to fix multiple issues with build client and server on local
  content/en/docs/collector/getting-started.md
Labels: docs:collector

#1162 Ensure configuration examples are illustrative but still secure
  content/en/docs/collector/configuration.md
Labels: docs:collector

#1238 .gitignore: add `.DS_Store`
  .gitignore
Labels: infrastructure

#1241 Upgrade NPM packages, including Hugo@0.96.0
  Makefile
  package.json
Labels: infrastructure
