Repository open-telemetry/opentelemetry.io, pull requests merged in 2022-08, with the labels that each got.

#1588 Social-media image: use colored stacked logo
  config.yaml
  layouts/index.redirects
  static/img/social/logo-wordmark-001.png
Labels: infrastructure

#1617 Address accessibility issue of link to instrumentation
  content/en/_index.md
Labels: ux

#1628 Hugo config: use placeholder for GA ID
  config.yaml
Labels: infrastructure

#1644 Upgrade netlify-cli
  package.json
Labels: dependencies, infrastructure

#1638 Registry: accessibility fix list
  layouts/registry/list.html
Labels: accessibility
