Repository open-telemetry/opentelemetry.io, pull requests merged in 2023-03, with the labels that each got.

#2440 SCSS variable cleanup in prep for Docsy upgrade
  assets/scss/_registry.scss
  assets/scss/_variables_project.scss
Labels: cleanup/refactoring, design/style

#2447 Add comment to all Docsy file overrides
  assets/scss/_styles_project.scss
  layouts/_default/baseof.html
  layouts/partials/favicons.html
Labels: cleanup/refactoring, docsy

#2445 Check formatting as a GH action
  .github/workflows/check-formatting.yml
  package.json
Labels: infrastructure

#2455 Upgrade Hugo to 0.111.1 and fix doc issues
  content/en/blog/2022/k8s-otel-expose/index.md
  content/en/docs/instrumentation/cpp/_index.md
  content/en/docs/instrumentation/erlang/_index.md
  content/en/docs/instrumentation/java/_index.md
  content/en/docs/instrumentation/js/_index.md
  content/en/docs/instrumentation/net/_index.md
  content/en/docs/instrumentation/php/_index.md
  content/en/docs/instrumentation/python/_index.md
  content/en/docs/instrumentation/ruby/_index.md
  content/en/docs/instrumentation/rust/_index.md
  content/en/docs/instrumentation/swift/_index.md
  package.json
Labels: dependencies, cleanup/refactoring

#2476 Link to local spec pages
  content/en/blog/2022/debug-otel-with-otel/index.md
  content/en/blog/2022/instrument-kafka-clients/index.md
  content/en/blog/2023/http-conventions-stability.md
  content/en/docs/collector/transforming-telemetry.md
  content/en/docs/demo/services/frontend.md
  content/en/docs/demo/services/load-generator.md
  content/en/docs/instrumentation/python/automatic/example.md
Labels: cleanup/refactoring

#2481 Add entry for missing OTel component color
  assets/scss/_registry.scss
  assets/scss/_variables_project.scss
Labels: design/style

#2477 Report issue if an external link is used to a local spec page
  layouts/_default/_markup/render-link.html
  scripts/content-modules/adjust-pages.pl
Labels: infrastructure

#2483 Copyedits of concepts/components.md
  content/en/docs/concepts/components.md
Labels: copyedit

#2484 Copyedits of collector-receiver-snmp.yml
  .vscode/cspell.json
  data/registry/collector-receiver-snmp.yml
Labels: copyedit

#2487 Collector getting-started copyedits
  .vscode/cspell.json
  content/en/docs/collector/getting-started.md
Labels: copyedit

#2499 Update dev dependencies in package.json
  package.json
Labels: dependencies, infrastructure

#2502 Link homepage demo CTA button to demo docs
  content/en/_index.md
  content/en/ecosystem/demo.md
Labels: demo

#2504 CI: add link-checking GH action, stop failing Netlify build on link-check issues
  .github/workflows/check-links.yml
  netlify.toml
  package.json
Labels: infrastructure

#2515 Ruby landing page cleanup of links to API ref and examples
  content/en/docs/instrumentation/ruby/_index.md
Labels: sig:ruby

#2449 PR-actions workflow with support for `/fix:format`
  .github/workflows/pr-actions.yml
Labels: infrastructure

#2522 Adjust blog to use local link path to homepage and demo
  content/en/blog/2022/otel-demo-app-nomad/index.md
  static/refcache.json
Labels: cleanup/refactoring

#2474 OTel Q&A Summary Blog Post - March 2023
  content/en/blog/2023/end-user-q-and-a-01.md
  content/en/blog/2023/end-user-q-and-a-02.md
  content/en/blog/2023/otel-in-focus-02.md
  static/refcache.json
Labels: blog

#2506 OpenTelemetry PHP Auto-Instrumentation blog post
  content/en/blog/2023/php-auto-instrumentation/index.md
  content/en/blog/2023/php-auto-instrumentation/laravel-auto.png
  content/en/blog/2023/php-auto-instrumentation/php-rel.png
  static/refcache.json
Labels: blog

#2473 Add ITRS Geneos as vendor
  content/en/ecosystem/vendors.md
  static/refcache.json
Labels: vendor-list

#2545 Fix link in PHP blog post
  content/en/blog/2023/php-auto-instrumentation/index.md
Labels: cleanup/refactoring

#2559 Docs flow fix for beginners, move "What is OpenTelemetry?" to top level
  .vscode/cspell.json
  content/en/_index.md
  content/en/blog/2022/otel-demo-app-nomad/index.md
  content/en/docs/_index.md
  content/en/docs/concepts/_index.md
  content/en/docs/concepts/glossary.md
  content/en/docs/concepts/observability-primer.md
  content/en/docs/concepts/signals/traces.md
  content/en/docs/demo/_index.md
  content/en/docs/getting-started/_index.md
  content/en/docs/getting-started/dev.md
  content/en/docs/getting-started/ops.md
  content/en/docs/instrumentation/erlang/instrumentation.md
  content/en/docs/instrumentation/java/automatic/annotations.md
  content/en/docs/instrumentation/java/manual.md
  content/en/docs/instrumentation/js/instrumentation.md
  content/en/docs/instrumentation/js/libraries.md
  content/en/docs/instrumentation/net/getting-started.md
  content/en/docs/instrumentation/net/libraries.md
  content/en/docs/instrumentation/net/manual.md
  content/en/docs/instrumentation/net/shim.md
  content/en/docs/instrumentation/php/manual.md
  content/en/docs/instrumentation/python/manual.md
  content/en/docs/instrumentation/ruby/manual.md
  content/en/docs/instrumentation/swift/manual.md
  content/en/docs/what-is-opentelemetry.md
Labels: copyedit, cleanup/refactoring
