Repository open-telemetry/opentelemetry.io, pull requests merged in 2023-05, with the labels that each got.

#2632 initial draft of lambda guidance
  content/en/docs/faas/_index.md
  content/en/docs/faas/lambda-auto-instrument.md
  content/en/docs/faas/lambda-collector.md
  content/en/docs/faas/lambda-manual-instrument.md
  static/refcache.json
Labels: enhancement, sig:faas

#2668 htmltest: bump up the cache expiry delay
  .htmltest.yml
Labels: infrastructure

#2667 Auto-update script: only match whole words, and other improvements
  .github/workflows/auto-update-versions.yml
  .github/workflows/scripts/auto-update-version.sh
Labels: infrastructure

#2676 Script adjust-pages.pl cleanup
  scripts/content-modules/adjust-pages.pl
Labels: infrastructure, cleanup/refactoring

#2694 NPM scripts: serve using Hugo, and normalize format cmd names
  .github/workflows/check-format.yml
  CONTRIBUTING.md
  Makefile
  archetypes/blog.md
  package.json
Labels: infrastructure

#2700 CI: NPM script tweaks
  Makefile
  package.json
Labels: infrastructure

#2764 Normalize link in exponential-histograms blog
  content/en/blog/2023/exponential-histograms.md
Labels: cleanup/refactoring

#2768 Auto-update spec: fetch tags
  .github/workflows/scripts/auto-update-version.sh
Labels: infrastructure

#2785 Semconv pages: don't warn about external links to spec
  scripts/content-modules/adjust-pages.pl
Labels: infrastructure

#2787 auto-update-version.sh fix: don't try to attach a label
  .github/workflows/scripts/auto-update-version.sh
Labels: infrastructure

#2726 add blog for lambda releases
  content/en/blog/2023/lambda-release.md
  static/refcache.json
Labels: sig:faas

#2798 CI: ensure that serve script doesn't do prep work twice
  package.json
Labels: infrastructure

#2796 Move spec-status page to be immediately under /docs/specs
  content/en/docs/specs/status.md
  content/en/status.md
  scripts/content-modules/adjust-pages.pl
Labels: sig:spec

#2799 Link to OTLP spec
  content/en/blog/2022/exponential-histograms/index.md
  content/en/docs/collector/deployment/agent.md
  content/en/docs/collector/deployment/gateway.md
  content/en/docs/concepts/glossary.md
  content/en/docs/concepts/sdk-configuration/general-sdk-configuration.md
  content/en/docs/instrumentation/python/exporters.md
  hugo.yaml
Labels: cleanup/refactoring, sig:spec

#2806 Redirect Docs > Migration > OpenCensus to the Sunsetting OpenCensus blog
  content/en/blog/2023/sunsetting-opencensus.md
  content/en/docs/migration/opencensus.md
Labels: copyedit, cleanup/refactoring
