Repository open-telemetry/opentelemetry.io, pull requests merged in 2023-06, with the labels that each got.

#2815 Add cspell to devDeps
  package.json
Labels: dependencies, infrastructure

#2824 Drop postcss from devDep list and tweak scripts
  package.json
  scripts/content-modules/cp-pages.sh
Labels: dependencies, infrastructure

#2854 Reorg text-sharing shortcodes before we add more
  content/en/docs/collector/_index.md
  content/en/docs/collector/distributions.md
  content/en/docs/instrumentation/cpp/_index.md
  content/en/docs/instrumentation/erlang/_index.md
  content/en/docs/instrumentation/java/_index.md
  content/en/docs/instrumentation/js/_index.md
  content/en/docs/instrumentation/net/_index.md
  content/en/docs/instrumentation/php/_index.md
  content/en/docs/instrumentation/python/_index.md
  content/en/docs/instrumentation/ruby/_index.md
  content/en/docs/instrumentation/rust/_index.md
  content/en/docs/instrumentation/swift/_index.md
  layouts/partials/docs/latest-release.md
  layouts/shortcodes/docs/instrumentation/index-intro.md
  layouts/shortcodes/docs/latest-release.md
  layouts/shortcodes/lang_instrumentation_index_head.md
  templates/language-docs/_index.md
Labels: cleanup/refactoring

#2858 Run prettier over docs shortcodes
  .prettierignore
  layouts/shortcodes/docs/instrumentation/index-intro.md
Labels: infrastructure

#2857 OTel spec: link to local OTLP, and fix README link
  package.json
  scripts/content-modules/adjust-pages.pl
Labels: infrastructure, sig:spec

#2909 Fix build warning due to link in docs/concepts/signals/logs.md
  content/en/docs/concepts/signals/logs.md
Labels: cleanup/refactoring

#2914 Go > Getting started: add note about intentional error
  content/en/docs/instrumentation/go/getting-started.md
Labels: sig:go

#2917 Fix invalid HTML and warnings reported by Prettier
  content/en/docs/collector/configuration.md
  content/en/docs/instrumentation/cpp/_index.md
  content/en/docs/instrumentation/erlang/_index.md
  content/en/docs/instrumentation/go/_index.md
  content/en/docs/instrumentation/java/_index.md
  content/en/docs/instrumentation/js/_index.md
  content/en/docs/instrumentation/net/_index.md
  content/en/docs/instrumentation/php/_index.md
  content/en/docs/instrumentation/python/_index.md
  content/en/docs/instrumentation/ruby/_index.md
  content/en/docs/instrumentation/rust/_index.md
  content/en/docs/instrumentation/swift/_index.md
  layouts/shortcodes/registry-search-form.html
Labels: cleanup/refactoring

#2921 Add Node version constraint to package.json & update contrib notes
  CONTRIBUTING.md
  package.json
Labels: infrastructure, cleanup/refactoring

#2922 CONTRIBUTING page tweaks, mainly code-block lang
  CONTRIBUTING.md
Labels: cleanup/refactoring

#2920 Add SemConv spec under docs/specs (preview)
  content/en/docs/specs/semconv/_index.md
  hugo.yaml
  scripts/content-modules/cp-pages.sh
  static/refcache.json
Labels: sig:spec

#2929 Reorder specs
  content/en/docs/specs/status.md
  scripts/content-modules/adjust-pages.pl
Labels: sig:spec

#2930 Clean up refcache.json: drop 4xx status entries
  static/refcache.json
Labels: infrastructure, cleanup/refactoring

#2931 Update manual.md
  content/en/docs/instrumentation/net/manual.md
Labels: CLA: no

#2948 CI: gulp task in support of refcache cleanup & some refcache updates
  gulp-src/README.txt
  gulp-src/_util.js
  gulp-src/default.js
  gulp-src/prune.js
  gulpfile.js
  package.json
  static/refcache.json
Labels: infrastructure

#2952 Lambda-auto-instrument.md: fix link + copyedits
  content/en/docs/faas/lambda-auto-instrument.md
Labels: copyedit, cleanup/refactoring

#2954 Refresh refcache and fix broken external links into Java API
  .htmltest.yml
  content/en/community/end-user/otel-in-practice.md
  content/en/docs/instrumentation/java/automatic/annotations.md
  static/refcache.json
Labels: infrastructure

#2955 Normalize CODEOWNERS entries to use -approvers
  .github/CODEOWNERS
Labels: infrastructure

#2959 Refcache refresh and 404 link fixes
  .htmltest.yml
  static/refcache.json
Labels: infrastructure

#2960 Refcache refresh (final for 23Q2) + prune task updated options and features
  gulp-src/prune.js
  static/refcache.json
Labels: infrastructure
