Repository open-telemetry/opentelemetry.io, pull requests merged in 2023-07, with the labels that each got.

#2978 Enable website telemetry in production only
  layouts/partials/hooks/body-end.html
Labels: analytics-and-seo

#3003 Update .prettierignore: drop .gitignore entries + comment tweak
  .prettierignore
Labels: infrastructure, cleanup/refactoring

#3007 CI: cache dependencies for check-format GH action
  .github/workflows/check-format.yml
Labels: infrastructure

#3012 Adjust-pages: link to local OTel spec for main and current vers + other fixes
  scripts/content-modules/adjust-pages.pl
Labels: infrastructure, sig:spec

#3019 Enforce kebab-case in file and folder names for main content and drops unused assets
  .github/workflows/check-format.yml
  assets/img/blog_card.jpg
  assets/img/twitch_card.jpg
  assets/img/yt_card.jpg
  content/en/blog/2019/opentelemetry-governance-committee-explained/index.md
  content/en/blog/2019/opentelemetry-governance-committee-explained/watering-can.jpeg
  content/en/blog/2022/opamp/index.md
  content/en/blog/2022/opamp/opamp-server-agent-config.png
  content/en/blog/2022/opamp/opamp-server-no-agents.png
  content/en/blog/2022/opamp/opamp-server-supervisor-agent-relations.png
  content/en/blog/2022/tail-sampling/backend-visual-errors-and-random.png
  content/en/blog/2022/tail-sampling/backend-visual-errors-only.png
  content/en/blog/2022/tail-sampling/index.md
  content/en/blog/2022/tail-sampling/tail-sampling-process.png
  content/en/blog/2022/tail-sampling/traces-venn-diagram.png
  content/en/docs/collector/deployment/agent.md
  content/en/docs/collector/deployment/gateway.md
  content/en/docs/collector/deployment/no-collector.md
  content/en/docs/collector/img/otel-agent-sdk.svg
  content/en/docs/collector/img/otel-gateway-sdk.svg
  content/en/docs/collector/img/otel-sdk.png
  content/en/docs/collector/img/otel-sdk.svg
  package.json
  static/img/logos/Node.js_logo.svg
  static/img/logos/Spring_Framework_Logo_2018.svg
  static/img/logos/zipkin-symbol.svg
  static/img/oteltuessplash-sm.png
  static/img/span-visualization.png
Labels: infrastructure

#3022 Adjust-pages: fix regex to avoid warning + tweak alias order
  content/en/ecosystem/registry/_index.md
  scripts/content-modules/adjust-pages.pl
Labels: infrastructure

#3058 Mention need to install SDK
  content/en/docs/instrumentation/php/automatic.md
Labels: sig:php

#3041 Create end-user-q-and-a-04.md
  content/en/blog/2023/end-user-q-and-a-04.md
  static/refcache.json
Labels: blog, sig:enduser

#3069 [CI] Ensure that lint-md has right exit code
  gulp-src/lint-md.js
Labels: infrastructure

#3078 Refactoring of data/instrumentation.yaml and associated shortcodes
  data/instrumentation.yaml
  layouts/shortcodes/docs/instrumentation/index-intro.md
  layouts/shortcodes/logs-support-table.md
  layouts/shortcodes/metrics-support-table.md
  layouts/shortcodes/sampling-support-list.md
  layouts/shortcodes/telemetry-support-table.md
Labels: infrastructure

#3084 CI: make netlify-cli optional
  .github/workflows/check-format.yml
  .github/workflows/check-links.yml
  .github/workflows/check-text.yml
  .github/workflows/pr-actions.yml
  package.json
Labels: infrastructure

#3053 Submit blog post about tracetesting the OTel demo
  content/en/blog/2023/testing-otel-demo/checkout-formatted.png
  content/en/blog/2023/testing-otel-demo/email-success-formatted-2.png
  content/en/blog/2023/testing-otel-demo/email-under-checkout-formatted.png
  content/en/blog/2023/testing-otel-demo/index.md
  content/en/blog/2023/testing-otel-demo/single-email-formatted.png
  content/en/blog/2023/testing-otel-demo/trace-based-testing-diagram.png
  static/refcache.json
Labels: blog

#3101 [CI] remove global dict words from page-local dictionaries + handle more cases
  content/en/_index.md
  content/en/blog/2022/apisix/index.md
  content/en/blog/2022/exponential-histograms/index.md
  content/en/blog/2022/go-web-app-instrumentation/index.md
  content/en/blog/2022/instrument-apache-httpd-server/index.md
  content/en/blog/2022/k8s-metadata/index.md
  content/en/blog/2022/knative/index.md
  content/en/blog/2022/otel-demo-app-nomad/index.md
  content/en/blog/2022/otel-tuesday-v1-sunset.md
  content/en/blog/2022/troubleshooting-nodejs.md
  content/en/blog/2023/end-user-q-and-a-03.md
  content/en/blog/2023/kubecon-eu.md
  content/en/blog/2023/php-auto-instrumentation/index.md
  content/en/docs/acknowledgements/_index.md
  content/en/docs/collector/configuration.md
  content/en/docs/collector/getting-started.md
  content/en/docs/collector/trace-receiver.md
  content/en/docs/demo/requirements/architecture.md
  content/en/docs/demo/scenarios/recommendation-cache/index.md
  content/en/docs/instrumentation/cpp/exporters.md
  content/en/docs/instrumentation/cpp/getting-started.md
  content/en/docs/instrumentation/erlang/exporters.md
  content/en/docs/instrumentation/go/exporters.md
  content/en/docs/instrumentation/go/getting-started.md
  content/en/docs/instrumentation/java/automatic/_index.md
  content/en/docs/instrumentation/java/automatic/agent-config.md
  content/en/docs/instrumentation/java/getting-started.md
  content/en/docs/instrumentation/js/automatic/module-config.md
  content/en/docs/instrumentation/js/exporters.md
  content/en/docs/instrumentation/js/propagation.md
  content/en/docs/instrumentation/net/exporters.md
  content/en/docs/instrumentation/net/manual.md
  content/en/docs/instrumentation/php/_index.md
  content/en/docs/instrumentation/php/automatic.md
  content/en/docs/instrumentation/python/exporters.md
  content/en/docs/instrumentation/ruby/exporters.md
  content/en/docs/instrumentation/rust/_index.md
  content/en/docs/kubernetes/helm/collector.md
  content/en/docs/migration/opentracing.md
  scripts/normalize-cspell-front-matter.pl
Labels: infrastructure

#3103 [CI] Clone submodules more deeply for `/fix:refache`
  .github/workflows/pr-actions.yml
Labels: infrastructure

#3016 added documentation for creating a basic connector
  content/en/docs/collector/build-connector.md
  content/en/docs/collector/img/otel-collector-after-connector.png
  content/en/docs/collector/img/otel-collector-before-connector.png
  static/refcache.json
Labels: sig:collector

#3115 [CI] Markdown lint: drop unnecessary config; add lang to code-fences
  .markdownlint.json
  CONTRIBUTING.md
  content/en/blog/2022/otel-demo-app-nomad/index.md
  content/en/blog/2023/exponential-histograms.md
  content/en/blog/2023/k8s-runtime-observability/index.md
  content/en/docs/collector/build-connector.md
  content/en/docs/instrumentation/go/getting-started.md
  content/en/docs/instrumentation/net/getting-started.md
  content/en/docs/instrumentation/net/libraries.md
  content/en/docs/instrumentation/net/manual.md
  content/en/docs/instrumentation/net/shim.md
  content/en/docs/instrumentation/php/automatic.md
  content/en/docs/instrumentation/ruby/manual.md
  content/en/docs/kubernetes/operator/automatic.md
Labels: cleanup/refactoring
