Repository open-telemetry/opentelemetry.io, pull requests merged in 2023-10, with the labels that each got.

#3385 [CI] Spec vers: clone deep enough to find tag
  .github/workflows/auto-update-versions.yml
Labels: infrastructure

#3417 Support page-relative aliases
  content/en/blog/2022/gc-candidates.md
  content/en/blog/2022/gc-elections.md
  content/en/blog/2023/end-user-discussions-01.md
  content/en/blog/2023/gc-elections.md
  content/en/blog/2023/new-apac-meetings.md
  content/en/docs/collector/_index.md
  content/en/docs/concepts/_index.md
  content/en/docs/concepts/components.md
  content/en/docs/concepts/instrumentation/_index.md
  content/en/docs/concepts/instrumentation/libraries.md
  content/en/docs/demo/architecture.md
  content/en/docs/demo/docker-deployment.md
  content/en/docs/demo/feature-flags.md
  content/en/docs/demo/features.md
  content/en/docs/demo/kubernetes-deployment.md
  content/en/docs/demo/manual-span-attributes.md
  content/en/docs/demo/metric-features.md
  content/en/docs/demo/requirements/application.md
  content/en/docs/demo/requirements/architecture.md
  content/en/docs/demo/requirements/opentelemetry.md
  content/en/docs/demo/requirements/system.md
  content/en/docs/demo/scenarios/recommendation-cache/index.md
  content/en/docs/demo/screenshots/index.md
  content/en/docs/demo/service-table.md
  content/en/docs/demo/services/accounting.md
  content/en/docs/demo/services/ad.md
  content/en/docs/demo/services/cart.md
  content/en/docs/demo/services/checkout.md
  content/en/docs/demo/services/currency.md
  content/en/docs/demo/services/email.md
  content/en/docs/demo/services/feature-flag.md
  content/en/docs/demo/services/fraud-detection.md
  content/en/docs/demo/services/frontend-proxy.md
  content/en/docs/demo/services/load-generator.md
  content/en/docs/demo/services/payment.md
  content/en/docs/demo/services/product-catalog.md
  content/en/docs/demo/services/quote.md
  content/en/docs/demo/services/recommendation.md
  content/en/docs/demo/services/shipping.md
  content/en/docs/demo/trace-features.md
  content/en/docs/instrumentation/erlang/manual.md
  content/en/docs/instrumentation/go/exporters.md
  content/en/docs/instrumentation/java/automatic/annotations.md
  content/en/docs/instrumentation/java/automatic/extensions.md
  content/en/docs/instrumentation/js/context.md
  content/en/docs/instrumentation/js/examples.md
  content/en/docs/instrumentation/js/propagation.md
  content/en/docs/instrumentation/php/getting-started.md
  content/en/docs/instrumentation/ruby/automatic.md
  content/en/docs/instrumentation/ruby/getting-started.md
  content/en/docs/specs/_index.md
  content/en/docs/specs/status.md
  layouts/index.redirects
Labels: infrastructure

#3405 Blog post summary: The Evolution of Observability Panel Discussion
  content/en/blog/2023/euwg-future-of-observability-panel.md
  static/refcache.json
Labels: blog

#3422 Registry: add instrumentation-go-sqs
  data/registry/instrumentation-go-sqs.yml
  static/refcache.json
Labels: CLA: no

#3464 [CI] Update package engines.node to 20.x to fix build warning
  package.json
Labels: infrastructure
