Repository open-telemetry/opentelemetry.io, pull requests merged in 2023-02, with the labels that each got.

#2252 Final move of registry into ecosystem section, and fix keyword search
  .htmltest.yml
  assets/js/registrySearch.js
  assets/scss/_styles_project.scss
  content/en/ecosystem/registry.md
  content/en/ecosystem/registry/_index.md
  layouts/ecosystem/registry.json.json
  layouts/index.redirects
  layouts/registry/list.json.json
  layouts/shortcodes/registry-search-form.html
Labels: cleanup/refactoring, registry

#2251 Update blog-post submission instructions
  README.md
Labels: blog

#2255 Use canonical path to registry throughout the website
  .htmltest.yml
  content/en/blog/2022/apisix/index.md
  content/en/docs/collector/configuration.md
  content/en/docs/concepts/distributions.md
  content/en/docs/concepts/instrumenting-library.md
  content/en/docs/concepts/instrumenting.md
  content/en/docs/instrumentation/erlang/getting-started.md
  content/en/docs/instrumentation/erlang/instrumentation.md
  content/en/docs/instrumentation/java/manual.md
  content/en/docs/instrumentation/js/getting-started/nodejs.md
  content/en/docs/instrumentation/js/libraries.md
  content/en/docs/instrumentation/net/libraries.md
  content/en/docs/instrumentation/other/_index.md
  content/en/docs/instrumentation/python/_index.md
  content/en/docs/instrumentation/python/automatic/_index.md
  content/en/ecosystem/registry/_index.md
Labels: cleanup/refactoring

#2266 Update check-collector-version.sh: support --dry-run and more
  .github/workflows/scripts/check-collector-version.sh
Labels: infrastructure

#2258 Delete unused nav.yaml data file
  data/nav.yaml
Labels: cleanup/refactoring

#2279 check-collector-version.sh: fix for Linux sed
  .github/workflows/scripts/check-collector-version.sh
Labels: infrastructure

#2276 Update CODEOWNERS: add demo docs, and sort entries
  .github/CODEOWNERS
Labels: infrastructure

#2275 Demo docs: left-nav fixes, adjusted linkTitles and more
  content/en/docs/demo/_index.md
  content/en/docs/demo/current_architecture.md
  content/en/docs/demo/demo_features.md
  content/en/docs/demo/demo_screenshots.md
  content/en/docs/demo/docker_deployment.md
  content/en/docs/demo/forking.md
  content/en/docs/demo/kubernetes_deployment.md
  content/en/docs/demo/metric_service_features.md
  content/en/docs/demo/requirements/_index.md
  content/en/docs/demo/requirements/application_requirements.md
  content/en/docs/demo/requirements/architecture_requirements.md
  content/en/docs/demo/requirements/opentelemetry_requirements.md
  content/en/docs/demo/requirements/system_requirements.md
  content/en/docs/demo/scenarios/_index.md
  content/en/docs/demo/scenarios/recommendation_cache.md
  content/en/docs/demo/services/_index.md
  content/en/docs/demo/services/accountingservice.md
  content/en/docs/demo/services/adservice.md
  content/en/docs/demo/services/cartservice.md
  content/en/docs/demo/services/checkoutservice.md
  content/en/docs/demo/services/currencyservice.md
  content/en/docs/demo/services/emailservice.md
  content/en/docs/demo/services/featureflagservice.md
  content/en/docs/demo/services/frauddetectionservice.md
  content/en/docs/demo/services/frontendproxy.md
  content/en/docs/demo/services/paymentservice.md
  content/en/docs/demo/services/productcatalogservice.md
  content/en/docs/demo/services/quoteservice.md
  content/en/docs/demo/services/recommendationservice.md
  content/en/docs/demo/services/shippingservice.md
  content/en/docs/demo/trace_service_features.md
Labels: copyedit, cleanup/refactoring, demo

#2286 Prettier base config and NPM scripts in preparation for CI integration
  .prettierignore
  CONTRIBUTING.md
  README.md
  hugo.yaml
  package.json
Labels: infrastructure

#2290 CI: enable Prettier checking
  .gitpod.yml
  hugo.yaml
  package.json
Labels: infrastructure

#2293 Demo docs: rename pages to follow website conventions
  content/en/docs/demo/_index.md
  content/en/docs/demo/architecture.md
  content/en/docs/demo/docker-deployment.md
  content/en/docs/demo/feature-flags.md
  content/en/docs/demo/features.md
  content/en/docs/demo/kubernetes-deployment.md
  content/en/docs/demo/manual-span-attributes.md
  content/en/docs/demo/metric-features.md
  content/en/docs/demo/requirements/_index.md
  content/en/docs/demo/requirements/application.md
  content/en/docs/demo/requirements/architecture.md
  content/en/docs/demo/requirements/opentelemetry.md
  content/en/docs/demo/requirements/system.md
  content/en/docs/demo/scenarios/recommendation-cache.md
  content/en/docs/demo/screenshots.md
  content/en/docs/demo/service-table.md
  content/en/docs/demo/service_table.md
  content/en/docs/demo/services/accounting.md
  content/en/docs/demo/services/ad.md
  content/en/docs/demo/services/cart.md
  content/en/docs/demo/services/checkout.md
  content/en/docs/demo/services/currency.md
  content/en/docs/demo/services/email.md
  content/en/docs/demo/services/feature-flag.md
  content/en/docs/demo/services/fraud-detection.md
  content/en/docs/demo/services/frontend-proxy.md
  content/en/docs/demo/services/load-generator.md
  content/en/docs/demo/services/payment.md
  content/en/docs/demo/services/product-catalog.md
  content/en/docs/demo/services/quote.md
  content/en/docs/demo/services/recommendation.md
  content/en/docs/demo/services/shipping.md
  content/en/docs/demo/trace-features.md
Labels: cleanup/refactoring

#2288 Demo service feature tables: recover icons
  content/en/docs/demo/metric-features.md
  content/en/docs/demo/trace-features.md
Labels: docs, cleanup/refactoring, demo

#2292 Run Prettifier on SCSS assets
  .prettierignore
  assets/scss/_styles_project.scss
  assets/scss/_tabs.scss
  assets/scss/_variables_project.scss
Labels: cleanup/refactoring

#2309 Enable Prettier check over some /docs
  .prettierignore
  content/en/docs/_index.md
  content/en/docs/acknowledgements/_index.md
  content/en/docs/contribution-guidelines.md
  content/en/docs/getting-started/_index.md
  content/en/docs/getting-started/dev.md
  content/en/docs/getting-started/ops.md
  content/en/docs/k8s-operator/_index.md
  content/en/docs/migration/opentracing.md
  content/en/docs/reference/specification/status.md
  content/en/docs/workshop/resources.md
Labels: infrastructure, cleanup/refactoring

#2311 Enable Prettier check over Ecosystem
  .prettierignore
  .vscode/cspell.json
  content/en/ecosystem/demo.md
  content/en/ecosystem/integrations.md
  content/en/ecosystem/vendors.md
Labels: infrastructure, cleanup/refactoring

#2314 Drop `/docs/workshop` section and add redirect rule
  content/en/docs/_index.md
  content/en/docs/workshop/_index.md
  content/en/docs/workshop/resources.md
  package.json
Labels: cleanup/refactoring

#2318 Demo docs: fix architecture diagram layout
  assets/scss/_styles_project.scss
Labels: design/style, demo

#2320 Demo docs: fix mermaid diagram width on FF and Safari
  assets/scss/_styles_project.scss
Labels: design/style

#2327 Demo docs: final post-move cleanup
  README.md
  content/en/docs/demo/_index.md
  content/en/docs/demo/img/opentelemetry-logo-nav.png
Labels: cleanup/refactoring

#2316 Enable Prettier check over Community + minor copyedits
  .prettierignore
  content/en/community/_index.md
  content/en/community/end-user/_index.md
  content/en/community/end-user/discussion-group.md
  content/en/community/end-user/otel-in-practice.md
  content/en/community/end-user/slack-channel.md
  content/en/community/marketing-guidelines.md
  content/en/community/mission.md
Labels: infrastructure, cleanup/refactoring

#2335 Normalize front matter field name
  content/en/community/end-user/_index.md
  content/en/community/end-user/discussion-group.md
  content/en/community/end-user/otel-in-practice.md
  content/en/community/end-user/slack-channel.md
  content/en/docs/instrumentation/python/getting-started.md
Labels: cleanup/refactoring

#2338 Enable Prettier check over instrumentation/python
  .prettierignore
  content/en/docs/instrumentation/_index.md
  content/en/docs/instrumentation/python/_index.md
  content/en/docs/instrumentation/python/automatic/_index.md
  content/en/docs/instrumentation/python/automatic/example.md
  content/en/docs/instrumentation/python/cookbook.md
  content/en/docs/instrumentation/python/distro.md
  content/en/docs/instrumentation/python/exporters.md
  content/en/docs/instrumentation/python/getting-started.md
  content/en/docs/instrumentation/python/manual.md
  content/en/docs/instrumentation/python/mypy.md
Labels: infrastructure, cleanup/refactoring

#2346 Fix broken external links to demo docs
  content/en/blog/2022/announcing-opentelemetry-demo-release.md
  content/en/blog/2022/demo-announcement/index.md
  content/en/blog/2022/frontend-overhaul/index.md
  content/en/blog/2022/otel-demo-app-nomad/index.md
  content/en/blog/2023/jmx-metric-insight/index.md
  content/en/blog/2023/php-beta-release.md
  content/en/docs/demo/architecture.md
Labels: cleanup/refactoring

#2352 Java pages need only one version parameter
  content/en/docs/instrumentation/java/_index.md
  content/en/docs/instrumentation/java/manual.md
Labels: cleanup/refactoring

#2362 CI: check external links (excluding GH)
  .htmltest.yml
  .prettierignore
  Makefile
  content/en/blog/2022/end-user-discussion-group-apac/index.md
  content/en/blog/2022/otel-demo-app-nomad/index.md
  package.json
  static/favicons/site.webmanifest
  static/refcache.json
Labels: infrastructure, cleanup/refactoring

#2364 CI script changes to fail on diff
  CONTRIBUTING.md
  netlify.toml
  package.json
Labels: infrastructure

#2367 Relocate non-icon images from iconography
  content/en/docs/collector/_index.md
  content/en/docs/collector/img/otel-collector.svg
  content/en/docs/concepts/instrumenting-library/index.md
  content/en/docs/concepts/instrumenting-library/nested-spans.svg
  iconography/Reference_Architecture.svg
Labels: cleanup/refactoring

#2366 CI: check non-resource & non-issue related links into GitHub
  .htmltest.yml
  content/en/blog/2022/apisix/index.md
  content/en/docs/instrumentation/ruby/_index.md
  package.json
  static/refcache.json
Labels: infrastructure

#2371 Drop iconography/Otel_iconography.zip
  .htmltest.yml
  hugo.yaml
  iconography/Otel_iconography.zip
Labels: cleanup/refactoring

#2389 Enable Prettier check over instrumentation/cpp
  .prettierignore
  content/en/docs/instrumentation/cpp/exporters.md
  content/en/docs/instrumentation/cpp/getting-started.md
  content/en/docs/instrumentation/cpp/manual.md
Labels: infrastructure

#2298 Add link to interview/feedback sessions resource
  content/en/community/end-user/_index.md
Labels: blocked
