Repository open-telemetry/opentelemetry.io, pull requests merged in 2024-08, with the labels that each got.

#4927 docs: correct context in propagation.md
  content/en/docs/languages/js/propagation.md
Labels: sig:javascript, sig:js

#4901 [pt] feat: add localization concepts index portugues
  content/pt/docs/concepts/_index.md
Labels: lang:pt

#4936 Update internal telemetry metrics names
  content/en/docs/collector/internal-telemetry.md
Labels: sig:collector

#4940 [CI] Only report registry format errors by default
  gulp-src/validate-registry.js
  package.json
Labels: CI/infra

#4943 [CI] Netlify production sanity checks: ignore canonical links
  netlify.toml
  package.json
Labels: CI/infra

#4944 [infra] Adjust-pages script cleanup and semconv vers tweak
  scripts/content-modules/adjust-pages.pl
Labels: CI/infra

#4935 Add logs section to Ad Service
  content/en/docs/demo/services/ad.md
Labels: sig:demo

#4904 adding updated doc ruby lambda and environment variables for ruby lib…
  content/en/docs/faas/lambda-auto-instrument.md
  content/en/docs/languages/ruby/libraries.md
  static/refcache.json
Labels: sig:ruby

#4950 Fix example of container parser
  content/en/blog/2024/otel-collector-container-log-parser/index.md
Labels: blog

#4803 [Python] Edit propagation doc
  content/en/docs/languages/python/propagation.md
Labels: sig:python

#4952 rework php zero-code page
  content/en/docs/languages/php/exporters.md
  content/en/docs/languages/php/getting-started.md
  content/en/docs/zero-code/php.md
Labels: sig:php

#4958 [infra] Upgrade NPM packages and clean up entries
  package.json
Labels: dependencies, CI/infra

#4961 Fix golang metric exporter snafu
  content/en/docs/languages/go/exporters.md
Labels: sig:go

#4896 [pt] feat: add what is opentelemetry localization
  content/pt/docs/what-is-opentelemetry.md
Labels: lang:pt

#4965 [CI] GH action config tweak: spell-check all files
  .github/workflows/check-spelling.yml
Labels: CI/infra

#4964 [cleanup] Add autoinstrumentation into the main dictionary
  .cspell.yml
  content/en/blog/2023/otel-in-focus-09.md
  content/en/docs/concepts/signals/logs.md
  content/en/docs/kubernetes/operator/automatic.md
  content/en/docs/languages/js/getting-started/nodejs.md
  content/en/docs/languages/js/libraries.md
  content/en/docs/zero-code/net/nuget-packages.md
Labels: cleanup/refactoring, blog, sig:dotnet, sig:operator, sig:js

#4974 [CI] Run workflows on `merge_group`
  .github/workflows/check-format.yml
  .github/workflows/check-i18n.yml
  .github/workflows/check-links.yml
  .github/workflows/check-registry.yml
  .github/workflows/check-spelling.yml
  .github/workflows/check-text.yml
Labels: CI/infra

#4976 [infra] Fix spelling errors, update and sort local dict
  .cspell.yml
  content/en/blog/2022/tail-sampling/index.md
  content/en/docs/concepts/sampling/index.md
Labels: CI/infra

#4975 [CI] Try to get streetsidesoftware/cspell-action to play nice
  .github/workflows/check-spelling.yml
Labels: CI/infra

#4982 [CI][i18n] Spell check content/pt, and enable other dicts
  .cspell.yml
  .github/workflows/check-spelling.yml
  package.json
Labels: CI/infra, i18n, lang:pt

#4978 Fix contributor guide URL
  content/en/docs/contributing/_index.md
  content/en/docs/contributing/requirements.md
Labels: lang:zh, lang:ja

#4994 Bumps sidebar section-entry limit
  hugo.yaml
Labels: docsy

#4932 [Registry] Remove otelzerolog log bridge
  data/registry/log-bridge-go-zerolog.yml
Labels: sig:go, registry

#4998 Add OpenFGA to registry
  data/registry/application-integration-openfga.yml
  static/refcache.json
Labels: registry

#5004 Add jaeger to integrations
  data/registry/application-integration-go-jaeger.yml
  static/refcache.json
Labels: registry

#5005 Add mount points for es pages
  hugo.yaml
Labels: lang:es

#5008 [CI] Install cspell/dict before running cspell action
  .github/workflows/check-spelling.yml
  package.json
Labels: CI/infra

#5009 Add cSpell excepctions for ES index
  content/es/_index.md
Labels: lang:es

#5010 [CI] Simplify cSpell dict install and other script tweaks
  .github/workflows/check-spelling.yml
  package.json
Labels: CI/infra

#5011 [infra] Move en words into separate word list, set up lists for es and pt
  .cspell.yml
  .cspell/en-words.txt
  .cspell/es-palabras.txt
  .cspell/pt-palavras.txt
  content/es/_index.md
  package.json
  scripts/normalize-cspell-front-matter.pl
Labels: CI/infra

#5014 [CI] Push back htmltest refcache expiry date, and fix a link
  .htmltest.yml
  data/ecosystem/vendors.yaml
  static/refcache.json
Labels: CI/infra

#4980 [pt] Add pt/content/docs/getting-started
  content/pt/docs/getting-started/_index.md
  content/pt/docs/getting-started/dev.md
  content/pt/docs/getting-started/ops.md
Labels: lang:pt

#4920 [zh] translate the observability primer
  content/zh/docs/concepts/observability-primer.md
Labels: lang:zh

#4969 Update getting-started.md
  content/en/docs/languages/erlang/getting-started.md
Labels: sig:erlang

#4984 [pt] Add /content/pt/docs/concepts/context-propagation.md
  content/pt/docs/concepts/context-propagation.md
Labels: lang:pt

#5032 Update and rename application-integration-python-apimetrics.yml to ap…
  data/registry/application-integration-python-apicontext.yml
Labels: registry

#5038 Update link to PrometheusHttpServer in prometheus-setup.md
  layouts/shortcodes/docs/languages/exporters/prometheus-setup.md
  static/refcache.json
Labels: sig:js

#5041 update links for new ocb binaries
  content/en/docs/collector/custom-collector.md
  static/refcache.json
Labels: sig:collector

#5046 Convert post on OTel governance to Markdown and publish it
  content/en/blog/2024/otel-governance/index.md
  static/refcache.json
Labels: blog

#5045 Define who is part of the Fix Team
  content/en/docs/security/security-response.md
Labels: sig:security

#5050 Update .NET tracing shim to correctly set span status
  content/en/docs/languages/net/shim.md
Labels: sig:dotnet

#5052 Remove random 'a' character in java instrumentation
  content/en/docs/languages/java/instrumentation.md
Labels: sig:java

#4996 OTel Docs Localized Announcement Blog Post
  .cspell/en-words.txt
  content/en/announcements/otel-localized.md
  content/en/blog/2024/docs-localized.md
Labels: blog

#5044 [ja] Add the localization announcement in Japanese
  content/ja/announcements/_index.md
  content/ja/announcements/otel-localized.md
  content/ja/blog/2024/_index.md
  content/ja/blog/2024/docs-localized.md
  content/ja/blog/_index.md
Labels: lang:ja

#5067 Add SAP Cloud Logging Exporter to registry
  data/registry/exporter-js-sap-cloud-logging.yml
  static/refcache.json
Labels: registry

#5074 Add cspell:ignore to registry entry
  data/registry/exporter-js-sap-cloud-logging.yml
Labels: registry

#5076 [ja] Fix the link to the contribution guide
  content/ja/docs/contributing/_index.md
Labels: lang:ja

#5070 [zh] Update what-is-opentelemetry.md
  content/zh/docs/what-is-opentelemetry.md
Labels: lang:zh

#5060 [zh] tranlate java language index
  content/zh/docs/languages/java/_index.md
Labels: lang:zh

#4879 [ja] add Japanese translation of quick start of collector
  content/ja/docs/collector/quick-start.md
Labels: lang:ja

#5088 [CI] Adjust submodule DEPTH uniformly across scripts
  .github/workflows/auto-update-versions.yml
  .github/workflows/pr-actions.yml
  package.json
Labels: CI/infra

#4997 [pt] Add pt/content/docs/concepts/observability-primer.md
  content/pt/docs/concepts/observability-primer.md
Labels: lang:pt

#5057 [es] feature: concepts - spanish translation
  content/es/docs/concepts/_index.md
Labels: lang:es

#5055 [es] kubernetes - spanish translation
  content/es/docs/kubernetes/_index.md
Labels: lang:es

#5054 [es] feature: getting started - spanish translation
  content/es/docs/getting-started/_index.md
Labels: lang:es

#5019 [pt] Add /pt/docs/concepts/signals/trace.md
  content/pt/docs/concepts/signals/traces.md
Labels: lang:pt

#5035 [pt] Localize otel-localized announcement page to Portuguese (Brazil)
  content/pt/announcements/_index.md
  content/pt/announcements/otel-localized.md
  content/pt/blog/2024/_index.md
  content/pt/blog/2024/docs-localized.md
  content/pt/blog/_index.md
Labels: blog, lang:pt

#5096 Create instrumentation-go-kafka.yml
  data/registry/instrumentation-go-kafka.yml
  static/refcache.json
Labels: registry

#5093 [pt] Add content/pt/docs/concepts/instrumentation/code-based.md
  content/pt/docs/concepts/instrumentation/code-based.md
Labels: lang:pt

#5100 Fix name of jaeger_remote polling interval property
  content/en/docs/languages/sdk-configuration/general.md
Labels: sig:java

#5047 [pt] Add /content/pt/docs/concepts/semantic-conventions.md
  content/pt/docs/concepts/semantic-conventions.md
Labels: lang:pt

#5106 Update NPM packages, including Hugo to 0.133.0
  package.json
Labels: CI/infra

#5105 Add context import to examples that use "context"
  content/en/docs/languages/go/exporters.md
Labels: sig:go

#5104 Add Go OTLP over gRPC exporter section
  content/en/docs/languages/go/exporters.md
  static/refcache.json
Labels: sig:go

#5087 Add blog post for go.opentelemetry.io switch
  content/en/blog/2024/go-opentelemetry-io.md
  static/refcache.json
Labels: blog

#5079 Add Checkmk App Integration Into the Registry
  data/registry/application-integration-python-checkmk.yml
  static/refcache.json
Labels: registry

#5058 [es] feature: contributing - spanish translation
  content/es/docs/contributing/_index.md
Labels: lang:es

#5112 [zh] add blog docs-localized.md
  content/zh/blogs/2024/_index.md
  content/zh/blogs/2024/docs-localized.md
  content/zh/blogs/_index.md
Labels: lang:zh

#5053 [es] feature: demo structure - spanish translation
  content/es/docs/demo/_index.md
Labels: lang:es

#5118 Custom collector page: link to tagged releases
  content/en/docs/collector/custom-collector.md
  static/refcache.json
Labels: sig:collector

#5122 [CI] After a `fix:*` command, tell user to rerun full checks
  .github/workflows/pr-actions.yml
Labels: CI/infra

#5126 [CI] PR-actions: escape PR comment special char
  .github/workflows/pr-actions.yml
Labels: CI/infra

#5116 Mention sync gauge in Otel Go metrics docs
  content/en/docs/languages/go/instrumentation.md
Labels: sig:go

#5127 [CI] PR-actions: multiline comment fix
  .github/workflows/pr-actions.yml
Labels: CI/infra

#5128 Create Haystack OpenInference Registry Entry
  data/registry/instrumentation-python-haystack-openinference.yml
Labels: registry
