Repository open-telemetry/opentelemetry.io, pull requests merged in 2025-10, with the labels that each got.

#7951 Refcache refresh
  static/refcache.json
Labels: CI/infra

#7949 [CI] Spec integration workflow fix: ignore link-check failures when updating refcache
  .github/workflows/update-semconv-integration-branch.yml
  .github/workflows/update-spec-integration-branch.yml
Labels: CI/infra, sig:spec

#7958 [CI] Update refcache-refresh.yml workflow to prune separately from update
  .github/workflows/refcache-refresh.yml
Labels: CI/infra

#7938 feat: add otel_upgrade_helper to registry
  data/registry/tools-otel-upgrade-helper.yml
  static/refcache.json
Labels: registry

#7903 [Blog Post] Android road to stable
  content/en/blog/2025/android-road-to-stable/demo-app1.png
  content/en/blog/2025/android-road-to-stable/demo-app2.png
  content/en/blog/2025/android-road-to-stable/demo-app3.png
  content/en/blog/2025/android-road-to-stable/index.md
  content/en/blog/2025/android-road-to-stable/kotlin1.png
  content/en/blog/2025/android-road-to-stable/kotlin2.png
  static/refcache.json
Labels: blog

#7968 Create KubeCon NA 2025 blog post
  content/en/announcements/kubecon-na.md
  content/en/blog/2025/kubecon-na.md
  static/refcache.json
Labels: blog

#7977 Upgrade to Hugo 0.150.1
  package.json
Labels: dependencies, CI/infra

#7941 fix: Custom Collector Dockfile will not build
  content/en/docs/collector/custom-collector.md
Labels: sig:collector

#7864 docs(es): add first version of Spanish (MX) translation for OBI
  content/es/docs/zero-code/obi/_index.md
Labels: sig-approval-missing, lang:es

#7840 [es] - spanish localization of content/es/docs/zero-code/_index
  content/es/docs/zero-code/_index.md
Labels: sig-approval-missing, lang:es

#7980 [CI] refcache-refresh.yml fixes: add GH token, and rebase arg
  .github/workflows/refcache-refresh.yml
Labels: CI/infra

#7989 [CI] workflows/refcache-refresh fix: use default count for scheduled runs too
  .github/workflows/refcache-refresh.yml
  package.json
Labels: CI/infra

#7991 [CI] Add clean-refcache script and run it
  .github/workflows/refcache-refresh.yml
  scripts/_clean-refcache-from-list.js
  scripts/_extract-external-links.js
  scripts/clean-refcache.js
  scripts/clean-refcache.sh
  static/refcache.json
Labels: CI/infra

#7999 [ro] feature /content/docs/getting-started/_index.md
  content/ro/docs/getting-started/_index.md
Labels: docs, ready-to-be-merged, lang:ro

#7924 [Blog] A day in the life of an OpenTelemetry maintainer
  content/en/blog/2025/day-opentelemetry-maintainer.md
  static/refcache.json
Labels: blog

#8015 [CI] Update contrib does, and fix script name
  content/en/docs/contributing/pr-checks.md
  scripts/double-check-refcache-4XX.mjs
Labels: CI/infra

#8017 [CI] refcache-refresh: fix chrome path
  .github/workflows/refcache-refresh.yml
  scripts/get-url-status.mjs
Labels: CI/infra

#7976 [es] Translation for opentelemetry.io/content/en/docs/zero-code/OBI
  content/es/docs/zero-code/obi/distributed-traces.md
  content/es/docs/zero-code/obi/ebpf-arch.svg
  content/es/docs/zero-code/obi/metrics.md
  content/es/docs/zero-code/obi/security.md
  content/es/docs/zero-code/obi/setup/_index.md
  content/es/docs/zero-code/obi/setup/docker.md
  content/es/docs/zero-code/obi/setup/kubernetes-helm.md
  content/es/docs/zero-code/obi/setup/kubernetes.md
  content/es/docs/zero-code/obi/setup/standalone.md
Labels: sig-approval-missing, lang:es

#8028 [CI] Refcache refresh: add verbose option
  .github/workflows/refcache-refresh.yml
  scripts/double-check-refcache-4XX.mjs
  scripts/get-url-status.mjs
Labels: CI/infra

#8034 [CI] Refcache refresh: fixes to npmjs logic
  scripts/get-url-status.mjs
Labels: CI/infra
