Repository open-telemetry/opentelemetry.io, pull requests merged in 2025-09, with the labels that each got.

#7675 Update content/en/docs/languages/java/sdk.md
  content/en/docs/languages/java/sdk.md
Labels: sig:java

#7692 feat [es] Correct docs/contributing/blog.md
  content/es/docs/contributing/blog.md
Labels: lang:es

#7693 feat [es] Correct docs/contributing/sig-practices.md
  content/es/docs/contributing/sig-practices.md
Labels: lang:es

#7672 Add `s2.dev` to vendors
  data/ecosystem/vendors.yaml
  static/refcache.json
Labels: ready-to-be-merged

#7486 [bn] localization of content content/bn/docs/demo/services/email.md
  .cspell/bn-words.txt
  content/bn/docs/demo/services/email.md
Labels: sig-approval-missing, lang:bn

#7485 Localization guidelines: update definitions for purely editorial content
  content/en/docs/contributing/localization.md
Labels: ready-to-be-merged

#7699 add link to form on adopters page
  content/en/ecosystem/adopters.md
  static/refcache.json
Labels: ready-to-be-merged

#7694 Update go getting-started examples in english
  content/en/docs/languages/go/getting-started.md
Labels: sig:go

#7703 Update go getting-started examples in non-english
  content/ja/docs/languages/go/getting-started.md
  content/pt/docs/languages/go/getting-started.md
  content/zh/docs/languages/go/getting-started.md
Labels: lang:zh, lang:ja, lang:pt, ready-to-be-merged

#7674 [zh] Add content/zh/docs/languages/java/sdk.md
  content/zh/docs/languages/java/sdk.md
Labels: lang:zh, ready-to-be-merged

#7701 Add Mackerel to vendors.yaml
  data/ecosystem/vendors.yaml
  static/refcache.json
Labels: ready-to-be-merged

#7496 [zh] Add collector/custom-collector.md
  content/zh/docs/collector/custom-collector.md
Labels: lang:zh, ready-to-be-merged

#7705 update php SemConv usage
  content/en/docs/languages/php/instrumentation.md
Labels: sig:php

#7523 [zh] Add collector/deployment/_index.md and agent.md
  content/zh/docs/collector/deployment/_index.md
  content/zh/docs/collector/deployment/agent.md
Labels: lang:zh, ready-to-be-merged

#7530 [zh] Add collector/building/_index and authenticator-extension
  content/zh/docs/collector/building/_index.md
  content/zh/docs/collector/building/authenticator-extension.md
Labels: lang:zh, ready-to-be-merged

#7724 [es] fix drift on content/es/docs/concepts/context-propagation.md
  content/es/docs/concepts/context-propagation.md
Labels: lang:es

#7725 [ja]Translate content/en/docs/zero-code/obi/setup/kubernetes.md
  content/ja/docs/zero-code/obi/setup/kubernetes.md
Labels: lang:ja, docs-approval-missing

#7726 [ja]Translate content/en/docs/zero-code/setup/standalone.md
  content/ja/docs/zero-code/obi/setup/standalone.md
Labels: lang:ja, docs-approval-missing

#7721 [ja]Translate content/en/docs/security/hosting-best-practices.md
  content/ja/docs/security/hosting-best-practices.md
Labels: lang:ja, docs-approval-missing

#7714 [ja]Translate content/en/docs/languages/ruby/sampling.md
  content/ja/docs/languages/ruby/sampling.md
Labels: lang:ja, docs-approval-missing

#7647 [bn] localization of content /services/shipping.md and services/image-provider.md
  .cspell/bn-words.txt
  content/bn/docs/demo/services/image-provider.md
  content/bn/docs/demo/services/shipping.md
Labels: sig-approval-missing, lang:bn

#7729 [zh] Add collector/management.md
  content/zh/docs/collector/management.md
Labels: sig-approval-missing, lang:zh

#7710 [zh] Add content/zh/docs/languages/java/configuration.md
  content/zh/docs/languages/java/configuration.md
Labels: lang:zh, ready-to-be-merged

#7081 Add known pre-fork server issue with metrics to Python Troubleshooting page
  content/en/docs/zero-code/python/troubleshooting.md
  static/refcache.json
Labels: sig:python

#7695 [bn] localization of content/en/docs/demo/services/cart/index.md
  .cspell/bn-words.txt
  content/bn/docs/demo/services/cart/index.md
Labels: lang:bn, ready-to-be-merged

#7681 [pt] Translate 'How to Name Your Metrics' blog post
  content/pt/blog/2025/how-to-name-your-metrics.md
Labels: blog, lang:pt, ready-to-be-merged

#7757 feat(blog): How to contribute to OpenTelemetry
  content/en/blog/2025/contribute-to-otel.md
  static/refcache.json
Labels: blog

#7758 [pt] Localization of blog post "How to Contribute to OpenTelemetry"
  content/pt/blog/2025/contribute-to-otel.md
Labels: lang:pt, ready-to-be-merged

#7763 [es] feature: concepts/signals/metrics - spanish translation
  content/es/docs/concepts/signals/metrics.md
Labels: sig-approval-missing, lang:es

#7682 [es] Translate 'How to Name Your Metrics' blog post
  .cspell/es-palabras.txt
  content/es/blog/2025/how-to-name-your-metrics.md
Labels: blog, sig-approval-missing, lang:es

#7787 Community events.md
  content/es/community/events.md
Labels: lang:es

#7774 Java Declarative config: intro
  content/en/docs/languages/sdk-configuration/declarative-configuration.md
  content/en/docs/zero-code/java/agent/declarative-configuration.md
  content/en/docs/zero-code/java/agent/disable.md
  content/en/docs/zero-code/java/agent/getting-started.md
  static/refcache.json
Labels: sig:java

#7782 add docs for new demo feature flag in email service
  content/en/docs/demo/feature-flags/_index.md
Labels: sig:demo, ready-to-be-merged

#7786 [uk] blog docs localized
  .cspell/uk-words.txt
  content/uk/blog/2024/_index.md
  content/uk/blog/2024/docs-localized.md
  content/uk/blog/_index.md
Labels: ready-to-be-merged, lang:uk

#7843 feat: add PagBank as an adopter
  data/ecosystem/adopters.yaml
Labels: ready-to-be-merged

#7851 Fix `page-drifted-msg.md` banner showing raw template code
  content/en/_includes/page-drifted-msg.md
  content/pt/_includes/page-drifted-msg.md
Labels: CI/infra, lang:pt

#7879 [CI] Check-links workflow use download-artifact merge-multiple
  .github/workflows/check-links.yml
  .github/workflows/scripts/check-refcache.sh
  content/en/docs/contributing/pr-checks.md
Labels: CI/infra

#7792 Add Oracle Database Metrics Exporter to the registry
  data/registry/tools-oracle-database-metrics-exporter.yml
  static/refcache.json
Labels: registry

#7881 [CI] Parallelize link checking - shard by locale group
  .github/workflows/check-links.yml
  package.json
Labels: CI/infra

#7895 [CI] Move workflow/scripts to be directly under .github
  .github/scripts/check-i18n-helper.sh
  .github/scripts/check-links-shard.sh
  .github/scripts/check-refcache.sh
  .github/scripts/textlint.sh
  .github/scripts/update-registry-versions.sh
  .github/workflows/auto-update-registry.yml
  .github/workflows/check-i18n.yml
  .github/workflows/check-links.yml
  .github/workflows/check-text.yml
Labels: CI/infra, cleanup/refactoring

#7886 Retrospective for September 25th incident on go.opentelemetry.io
  content/en/blog/2025/go-opentelemetry-io-expired-certificate.md
  static/refcache.json
Labels: blog

#7814 docs: add flagd-ui to demo services
  content/en/docs/demo/_index.md
  content/en/docs/demo/architecture.md
  content/en/docs/demo/services/_index.md
  content/en/docs/demo/services/flagd-ui.md
  static/refcache.json
Labels: sig:demo, sig-approval-missing

#7824 Add blog post entry for kotlin multiplatform
  content/en/blog/2025/kotlin-multiplatform-opentelemetry.md
  static/refcache.json
Labels: blog

#7892 [ja] fix: a drift file of content/ja/docs/security/_index.md
  content/ja/docs/security/_index.md
Labels: lang:ja, ready-to-be-merged

#7917 [ja] docs(i18n): translate content/en/docs/zero-code/java/agent/_index.md
  content/ja/docs/zero-code/java/agent/_index.md
Labels: lang:ja, ready-to-be-merged

#7944 [CI] Don't ignore shard link-check errors
  .github/scripts/check-links-shard.sh
  .github/workflows/check-links.yml
Labels: CI/infra

#7946 [ro] Fix link-check failures
  content/ro/docs/what-is-opentelemetry.md
Labels: lang:ro
