Repository open-telemetry/opentelemetry.io, pull requests merged in 2025-08, with the labels that each got.

#7452 [i18n] Move alert prose from `native-libraries` partial into an include file
  content/en/docs/languages/_includes/native-lib-alert.md
  content/en/docs/languages/java/instrumentation.md
  content/ja/docs/languages/java/instrumentation.md
  content/pt/docs/languages/java/instrumentation.md
  layouts/_partials/docs/native-libraries.md
  layouts/_partials/func/get-lang.html
Labels: i18n, sig:java, lang:ja, lang:pt

#7454 [zh] Add collector/resiliency.md
  content/zh/docs/collector/resiliency.md
Labels: lang:zh, docs-approval-missing

#7387 [fr] Translation of Zero Code Python docs
  .cspell/fr-mots.txt
  content/fr/docs/zero-code/python/_index.md
  content/fr/docs/zero-code/python/configuration.md
  content/fr/docs/zero-code/python/example.md
  content/fr/docs/zero-code/python/logs-example.md
  content/fr/docs/zero-code/python/operator.md
  content/fr/docs/zero-code/python/troubleshooting.md
  static/refcache.json
Labels: lang:fr, ready-to-be-merged

#7438 [zh] Add collector/quick-start.md
  content/zh/docs/collector/quick-start.md
Labels: lang:zh, ready-to-be-merged

#7422 [zh] Add content/zh/docs/languages/java/getting-started.md
  content/zh/docs/languages/java/getting-started.md
Labels: lang:zh, ready-to-be-merged

#7389 [fr] Translation of Zero Code Java docs
  .cspell/fr-mots.txt
  content/fr/docs/zero-code/java/_index.md
  content/fr/docs/zero-code/java/agent/_index.md
  content/fr/docs/zero-code/java/agent/annotations.md
  content/fr/docs/zero-code/java/agent/api.md
  content/fr/docs/zero-code/java/agent/configuration.md
  content/fr/docs/zero-code/java/agent/disable.md
  content/fr/docs/zero-code/java/agent/extensions.md
  content/fr/docs/zero-code/java/agent/getting-started.md
  content/fr/docs/zero-code/java/agent/instrumentation/_index.md
  content/fr/docs/zero-code/java/agent/instrumentation/http.md
  content/fr/docs/zero-code/java/agent/performance.md
  content/fr/docs/zero-code/java/agent/server-config.md
  content/fr/docs/zero-code/java/quarkus.md
  content/fr/docs/zero-code/java/spring-boot-starter/_index.md
  content/fr/docs/zero-code/java/spring-boot-starter/additional-instrumentations.md
  content/fr/docs/zero-code/java/spring-boot-starter/annotations.md
  content/fr/docs/zero-code/java/spring-boot-starter/api.md
  content/fr/docs/zero-code/java/spring-boot-starter/getting-started.md
  content/fr/docs/zero-code/java/spring-boot-starter/other-spring-autoconfig.md
  content/fr/docs/zero-code/java/spring-boot-starter/out-of-the-box-instrumentation.md
  content/fr/docs/zero-code/java/spring-boot-starter/sdk-configuration.md
Labels: lang:fr, ready-to-be-merged

#7388 [fr] Translation of Zero Code JS docs
  content/fr/docs/zero-code/js/_index.md
  content/fr/docs/zero-code/js/configuration.md
Labels: lang:fr, ready-to-be-merged

#7352 [bn] localization of content content/bn/docs/demo/architecture.md
  .cspell/bn-words.txt
  content/bn/docs/demo/architecture.md
Labels: sig-approval-missing, lang:bn, ready-to-be-merged

#7465 [zh] Improve a sampling desc text in sampling/index.md
  content/zh/docs/concepts/sampling/index.md
Labels: lang:zh, ready-to-be-merged

#7408 [ja] docs(i18n): fix drift of content/ja/docs/contributing/*.md files
  content/ja/docs/contributing/development.md
  content/ja/docs/contributing/issues.md
  content/ja/docs/contributing/prerequisites.md
  content/ja/docs/contributing/pull-requests.md
Labels: lang:ja, ready-to-be-merged

#7410 [ja] docs(i18n): fix drift of content/ja/docs/languages/go/*.md files
  content/ja/docs/languages/go/getting-started.md
  content/ja/docs/languages/go/instrumentation.md
Labels: lang:ja, ready-to-be-merged

#7467 Add Embrace Web SDK to list of distributions
  data/ecosystem/distributions.yaml
  static/refcache.json
Labels: ready-to-be-merged

#7473 Fix: update broken URL in content/en/docs/contributing/localization.md
  content/en/docs/contributing/localization.md
  content/es/docs/contributing/localization.md
  content/ja/docs/contributing/localization.md
  content/zh/docs/contributing/localization.md
  static/refcache.json
Labels: lang:zh, lang:ja, lang:es, docs-approval-missing

#7460 [pt] Localize content/pt/docs/contributing/localization.md
  content/pt/docs/contributing/localization.md
Labels: lang:pt, ready-to-be-merged

#7471 [zh] Add collector/transforming-telemetry.md
  content/zh/docs/collector/transforming-telemetry.md
Labels: lang:zh, ready-to-be-merged

#7493 [pt] add drifted_from_default to out-of-date pt pages
  content/pt/announcements/_index.md
  content/pt/docs/_includes/exporters/intro.md
  content/pt/docs/concepts/glossary.md
  content/pt/docs/concepts/instrumentation-scope/index.md
  content/pt/docs/concepts/resources/index.md
  content/pt/docs/concepts/signals/metrics.md
  content/pt/docs/concepts/signals/traces.md
  content/pt/docs/contributing/blog.md
  content/pt/docs/contributing/localization.md
  content/pt/docs/contributing/pr-checks.md
  content/pt/docs/contributing/prerequisites.md
  content/pt/docs/contributing/pull-requests.md
  content/pt/docs/contributing/style-guide.md
  content/pt/docs/languages/_includes/exporters/prometheus-setup.md
  content/pt/docs/languages/_includes/exporters/zipkin-setup.md
  content/pt/docs/languages/_index.md
  content/pt/docs/languages/go/api.md
  content/pt/docs/languages/go/examples.md
  content/pt/docs/languages/go/getting-started.md
  content/pt/docs/languages/go/instrumentation.md
  content/pt/docs/languages/go/registry.md
  content/pt/docs/languages/java/_index.md
  content/pt/docs/languages/java/instrumentation.md
  content/pt/docs/languages/js/getting-started/nodejs.md
  content/pt/docs/languages/python/_index.md
  content/pt/docs/languages/python/exporters.md
  content/pt/docs/languages/python/getting-started.md
  content/pt/docs/languages/sdk-configuration/general.md
  content/pt/docs/what-is-opentelemetry.md
  content/pt/ecosystem/distributions.md
  content/pt/ecosystem/integrations.md
  content/pt/ecosystem/registry/_index.md
Labels: lang:pt, ready-to-be-merged

#7323 feat: Translate to spanish: content/es/docs/concepts/semantic-convent…
  content/es/docs/concepts/semantic-conventions.md
Labels: lang:es, ready-to-be-merged

#7481 Rewording second paragraph in "Context" section of context propagation docs - Issue #6674
  content/en/docs/concepts/context-propagation.md
Labels: ready-to-be-merged

#7490 feat: [es] New translation - ecosystem folder
  content/es/ecosystem/_index.md
Labels: lang:es

#7472 Add blog for OTiP: Alibaba
  content/en/blog/2025/otip-alibaba.md
  static/refcache.json
Labels: blog

#7500 Update date of OTiP Alibaba blogpost
  content/en/blog/2025/otip-alibaba.md
Labels: blog

#7476 [pt] Localize pages under /content/en/community
  content/pt/community/_index.md
  content/pt/community/events.md
  content/pt/community/marketing-guidelines.md
  content/pt/community/members.md
Labels: lang:pt

#7431 feat: [es] New translation - /docs/languages/js
  content/es/docs/languages/js/_index.md
  content/es/docs/languages/js/getting-started/_index.md
  content/es/docs/languages/js/getting-started/browser.md
Labels: lang:es

#7511 [i18n] Move propagation.md from partials into an include file
  content/en/docs/languages/_includes/propagation.md
  content/en/docs/languages/erlang/propagation.md
  content/en/docs/languages/js/propagation.md
  content/en/docs/languages/php/propagation.md
  layouts/_partials/docs/propagation.md
  layouts/_shortcodes/docs/languages/propagation.md
Labels: i18n

#7515 add: status spanish translation
  content/es/status.md
Labels: lang:es

#7502 [ja]Translate content/en/docs/platforms/kubernetes/operator/troublesh…
  content/ja/docs/platforms/kubernetes/operator/troubleshooting/target-allocator.md
Labels: lang:ja, ready-to-be-merged

#7533 [ja]Translate content/en/docs/languages/_includes/instrumentation-int…
  content/ja/docs/languages/_includes/instrumentation-intro.md
Labels: lang:ja, ready-to-be-merged

#7518 Update OTel Demo architecture diagrams to match current collector config
  content/en/docs/demo/architecture.md
Labels: sig:demo, sig-approval-missing

#7556 add: docs/_includes resource-intro to spanish
  content/es/docs/_includes/resources-intro.md
Labels: lang:es

#7568 Update front matter to better hide OBI Helm chart page
  content/en/docs/zero-code/obi/setup/kubernetes-helm.md
Labels: sig:obi

#7578 update: docs/platform/kubernetes/_index
  content/es/docs/platforms/kubernetes/_index.md
Labels: lang:es

#7551 Update component-owners.yml
  .github/component-owners.yml
Labels: CI/infra, ready-to-be-merged

#7534 add: training page to spanish
  content/es/status.md
  content/es/training/index.md
Labels: sig-approval-missing, lang:es

#7576 [pt] Translate 'How to Name Your Spans' blog post
  content/pt/blog/2025/how-to-name-your-spans.md
Labels: blog, sig-approval-missing, lang:pt

#7592 [pt] Localize content/pt/training/index.md
  content/pt/training/index.md
Labels: sig-approval-missing, lang:pt

#7589 Blog to promote issue reactions
  content/en/blog/2025/issue-participation.md
  static/refcache.json
Labels: blog

#7598 [Infra] Add fix:refcache to auto-update-community-members.yml workflow
  .github/workflows/auto-update-community-members.yml
Labels: CI/infra

#7577 [es] Translate 'How to Name Your Spans' blog post
  content/es/blog/2025/how-to-name-your-spans.md
Labels: blog, sig-approval-missing, lang:es

#7363 [ja]Translate content/ja/docs/collector/troubleshooting.md
  content/ja/docs/collector/troubleshooting.md
Labels: lang:ja, docs-approval-missing

#7377 [bn] localization of content demo/services/accounting.md and demo/services/fraud-detection.md
  .cspell/bn-words.txt
  content/bn/docs/demo/services/accounting.md
  content/bn/docs/demo/services/fraud-detection.md
Labels: sig-approval-missing, lang:bn

#7617 [ja] docs(i18n): fix drift of content/ja/languages/sdk-configuration/general.md
  content/ja/docs/languages/sdk-configuration/general.md
Labels: lang:ja, ready-to-be-merged

#7632 fix Duplicate JavaScript filter in the Ecosystem Registry
  data/registry-schema.json
  data/registry/instrumentation-js-langchain.yml
  data/registry/instrumentation-js-openai.yml
Labels: registry

#7606 Fix JS/TS "getting started" code to work
  content/en/docs/languages/js/getting-started/nodejs.md
  static/refcache.json
Labels: sig:javascript, ready-to-be-merged

#7619 [ja] docs(i18n): translate content/en/docs/languages/_includes/span-status-preamble.md
  content/ja/docs/languages/_includes/span-status-preamble.md
Labels: sig-approval-missing, lang:ja

#7613 [ja] docs(i18n): fix drifted files of content/ja/docs/concepts/
  content/ja/docs/concepts/context-propagation.md
  content/ja/docs/concepts/semantic-conventions.md
  content/ja/docs/concepts/signals/metrics.md
Labels: sig-approval-missing, lang:ja

#7610 [ja] docs(i18n): fix drift of content/ja/docs/demo/architecture.md
  content/ja/docs/demo/architecture.md
Labels: sig-approval-missing, lang:ja

#7609 [ja] docs(i18n): fix drifted files of content/ja/docs/contributing/
  content/ja/docs/contributing/blog.md
  content/ja/docs/contributing/localization.md
  content/ja/docs/contributing/pr-checks.md
  content/ja/docs/contributing/style-guide.md
Labels: sig-approval-missing, lang:ja

#7161 [ja]Translate content/en/docs/platforms/kubernetes/operator/horizonta…
  content/ja/docs/platforms/kubernetes/operator/horizontal-pod-autoscaling.md
Labels: sig-approval-missing, lang:ja

#7255 [ja] add translation of collector/configuration
  content/ja/docs/collector/configuration.md
  content/ja/docs/collector/management.md
Labels: sig-approval-missing, lang:ja

#7643 feat [es] Create docs/contributing/blog.md
  content/es/docs/contributing/blog.md
Labels: lang:es

#7646 [ja]Translate content/en/docs/languages/_includes/libraries-intro.md
  content/ja/docs/languages/_includes/libraries-intro.md
Labels: sig-approval-missing, lang:ja

#7631 [es] Update drifted content for page content/es/_index.md
  content/es/_index.md
Labels: lang:es, ready-to-be-merged

#7625 [zh] Add content/zh/docs/languages/java/api.md
  content/zh/docs/languages/java/api.md
Labels: lang:zh, ready-to-be-merged

#7645 feat [es] Create docs/contributing/sig-practices.md
  content/es/docs/contributing/sig-practices.md
Labels: sig-approval-missing, lang:es

#7575 [i18n] Convert page-outdated banner into an include file
  content/en/_includes/page-drifted-msg.md
  layouts/docs/_td-content-after-header.html
Labels: CI/infra, lang:pt

#7630 [es] Translate 'How to Name Your Span Attributes' blog post
  content/es/blog/2025/how-to-name-your-span-attributes.md
Labels: blog, lang:es

#7164 [ja] docs(i18n): translate content/en/docs/languages/js/*.md files
  content/ja/docs/languages/_includes/exporters/jaeger.md
  content/ja/docs/languages/_includes/exporters/outro.md
  content/ja/docs/languages/_includes/exporters/prometheus-setup.md
  content/ja/docs/languages/_includes/exporters/zipkin-setup.md
  content/ja/docs/languages/_includes/native-lib-alert.md
  content/ja/docs/languages/_includes/propagation.md
  content/ja/docs/languages/js/_includes/browser-instrumentation-warning.md
  content/ja/docs/languages/js/_index.md
  content/ja/docs/languages/js/benchmarks.md
  content/ja/docs/languages/js/context.md
  content/ja/docs/languages/js/exporters.md
  content/ja/docs/languages/js/getting-started/_index.md
  content/ja/docs/languages/js/getting-started/browser.md
  content/ja/docs/languages/js/getting-started/nodejs.md
  content/ja/docs/languages/js/instrumentation.md
  content/ja/docs/languages/js/libraries.md
  content/ja/docs/languages/js/propagation.md
  content/ja/docs/languages/js/resources.md
  content/ja/docs/languages/js/sampling.md
  content/ja/docs/languages/js/serverless.md
Labels: sig-approval-missing, lang:ja

#7656 fix: typographical error about DefinitelyTyped
  content/en/docs/languages/js/_index.md
Labels: sig:javascript

#7651 feat [es] Create docs/contributing/acknowledgements.md
  content/es/docs/contributing/acknowledgements.md
Labels: lang:es, ready-to-be-merged

#7665 docs: fix link to deprecated crate
  content/en/docs/languages/rust/libraries.md
Labels: sig:rust

#7653 feat [es] Create docs/contributing/announcements.md
  content/es/docs/contributing/announcements.md
Labels: lang:es, ready-to-be-merged

#7618 [pt] Translate 'How to Name Your Span Attributes' blog post
  content/pt/blog/2025/how-to-name-your-span-attributes.md
Labels: blog, sig-approval-missing, lang:pt

#7537 Fix link for collector internal-telemetry config
  content/en/docs/collector/internal-telemetry.md
  static/refcache.json
Labels: sig:collector, ready-to-be-merged

#7670 Bump Go semconv package
  content/en/docs/languages/go/instrumentation.md
Labels: sig:go
